In [2]:
from sklearn import datasets
iris = datasets.load_iris()

In [17]:
iris.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [4]:
import numpy as np

In [40]:
a = np.array((1, 2, 3, 4))

In [41]:
a

array([1, 2, 3, 4])

In [42]:
w0 = 2*np.random.random((4, 5))-1
w1 = 2*np.random.random((5, 3))-1

In [10]:
w0

array([[0.63256784, 1.89094437, 0.29798741],
       [0.2883865 , 0.50642237, 1.5973138 ]])

In [11]:
w0.T

array([[0.63256784, 0.2883865 ],
       [1.89094437, 0.50642237],
       [0.29798741, 1.5973138 ]])

In [53]:
a.dot(iris.data[0].T)
n = 0.1

In [43]:
y_train = np.array((2, 3, 5))

In [22]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_deriv(x):
    return sigmoid(x)*(1 - sigmoid(x))

In [54]:
layer0 = np.array([iris.data[0]])
layer1 = sigmoid(np.dot(layer0, w0))
layer2 = sigmoid(np.dot(layer1, w1))

# обратное распространение(back propagation) с использованием градиентного спуска
layer2_error = y_train - layer2
layer2_delta = layer2_error * sigmoid_deriv(layer2)

layer1_error = layer2_delta.dot(w1.T)
layer1_delta = layer1_error * sigmoid_deriv(layer1)

w1 += layer1.T.dot(layer2_delta) * n
w0 += layer0.T.dot(layer1_delta) * n

In [55]:
layer2_error

array([[1.17722249, 2.5271528 , 4.42814672]])

In [56]:
layer2_delta

array([[0.24962177, 0.59774915, 1.02124554]])

In [62]:
w1

array([[ 0.8180802 ,  0.41429763, -0.86053517],
       [ 0.75063367, -0.13403397,  0.27908318],
       [ 0.34266321, -0.29930768,  0.41907539],
       [-0.10122121,  0.6538487 , -0.02359793],
       [ 0.9433007 , -0.73601894,  0.63293868]])

In [68]:
layer2_delta.dot(w1[0])

array([-0.42696103])

In [69]:
w1[0]

array([ 0.8180802 ,  0.41429763, -0.86053517])

In [70]:
w0[0]

array([-0.70886563,  0.76155628,  0.80695437,  0.8917752 ,  0.09754994])

In [73]:
w1[0][0] * layer2_delta[0][0] + w1[0][1] * layer2_delta[0][1] + w1[0][2] * layer2_delta[0][2]

-0.4269610284505093